# Generated by Django 5.1 on 2024-09-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=255)),
                ('cnn', models.CharField(blank=True, max_length=255, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('block_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.CharField(blank=True, max_length=255, null=True)),
                ('permit', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
