# Generated by Django 5.1 on 2024-09-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruckapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='block_lot',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='cnn',
            field=models.IntegerField(),
        ),
    ]
