# Generated by Django 5.1 on 2024-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruckapp', '0002_alter_foodtruck_block_alter_foodtruck_block_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='block_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='cnn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
