# Generated by Django 5.1 on 2024-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruckapp', '0004_alter_foodtruck_cnn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='block_lot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='cnn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
